export enum AchievementCategory {
  DELIVERY = 'DELIVERY',
  TECHNICAL = 'TECHNICAL',
  LEADERSHIP = 'LEADERSHIP',
  CUSTOMER_APPRECIATION = 'CUSTOMER_APPRECIATION',
  INNOVATION = 'INNOVATION',
  PROCESS_IMPROVEMENT = 'PROCESS_IMPROVEMENT',
}
