export enum NotificationType {
  PENDING_REVIEW = 'PENDING_REVIEW',
  GOAL_DEADLINE = 'GOAL_DEADLINE',
  PROMOTION_REVIEW = 'PROMOTION_REVIEW',
  MISSING_ONE_ON_ONE = 'MISSING_ONE_ON_ONE',
  LEARNING_EXPIRY = 'LEARNING_EXPIRY',
  CERTIFICATION_EXPIRY = 'CERTIFICATION_EXPIRY',
}
