export enum TalentCategory {
  FUTURE_LEADER = 'FUTURE_LEADER',
  HIGH_PERFORMER = 'HIGH_PERFORMER',
  CORE_CONTRIBUTOR = 'CORE_CONTRIBUTOR',
  EMERGING_TALENT = 'EMERGING_TALENT',
  UNDERPERFORMER = 'UNDERPERFORMER',
}
